### ISSUE TITLE
Improve water overall

### ISSUE THREAD

**Issue by Ahaeflig** [JonathanLink/icg-group1#20]
The way the uv coord of the water is translated in the fshader of the water in the branch waterNormalMap is totally not natural and needs to be improved.

CF SLIDES:
"A more interesting appearance for water can be obtained by applying a normal map to its surface.
The image above shows a snapshot and the normal map (a texture whose RGB components
represent normal orientations) that was used to generate the effect, while a brief video can be
downloaded here: http://lgg.epfl.ch/teaching/icg/waves.mp4. The dynamic effect in
the video can be obtained by translating the texture coordinates in time. Note that the geometry of
the water is completely flat! The shading, both Lambertian and specular highlights, are the result
of using the normals from the normal map instead of the ones of the sea geometry (which are
[ 0, 1, 0 ] everywhere) "

Shading looks better with the water normal map but not sure if it is completly correct need to check
Also a specular term might be needed for better effect as mentioned in the PDF

**Comment by pwalch** [comment]
Fixed.
